spring.application.name=parking
spring.datasource.url=jdbc:mariadb://localhost/parking?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=drop-and-create
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver